language: java
jdk:
  - oraclejdk8
  - openjdk8

before_deploy:
  - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

deploy:
  provider: releases
  file: target/distance4j-$VERSION.jar
  api_key:
    secure: $GITHUB_OATH_TOKEN
  skip_cleanup: true
  draft: true
  on:
    repo: jbujalance/Distance4J
    tags: true
    branch: master